spring:
  application:
    name: library-lending-service

server:
  port: 8090

db:
  url: jdbc:postgresql://localhost:5432/library_lending_service
  user: postgres
  password: password

crypto:
  secret-key: "<secret-key>"
  ALGORITHM: "HmacSHA256"